name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
